### ISSUE TITLE
program crashing when hitting -.0 long/lat values in elevation analyses

### ISSUE THREAD

**Issue by rscharn** [mtop/speciesgeocoder#43]
while running an analyses the program indicated the following error

subprocess.CalledProcessError: Command '['/home/local/git/geocoder/bin/gdallocationinfo_linux2', '-valonly', '-wgs84', '/usr/local/db/speciesgeocoder/Elevation/250m_worlddata/SRTM_W_250m.tif', '-78.77841', '-.0510693']' returned non-zero exit status 1

**Comment by mtop** [comment]
The stand alone version of gdal had problems with handling "-.0510693" (should be '-**0**.0510693'), but the GDAL python module can handle this so this is not a problem anymore.
